dockerversion: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eventory-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    networks:
      - eventory
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: eventory-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - eventory
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: eventory-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: eventory
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: eventory
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - eventory
    command: --default-authentication-plugin=mysql_native_password

networks:
  eventory:
    driver: bridge

volumes:
  dbdata:
    driver: local 